# Netlify Configuration for Generic Wellness Framework
# This file is automatically detected by Netlify for deployment settings

[build]
  # No build command needed - static files
  command = "echo 'No build required for static wellness framework'"
  # Publish the current directory
  publish = "."

# Redirect rules for SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/audio/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/graphics/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Environment variables (can be overridden in Netlify dashboard)
[context.production.environment]
  NODE_ENV = "production"
  APP_CONFIG = "examples/app-config.json"

[context.deploy-preview.environment]
  NODE_ENV = "development"
  APP_CONFIG = "examples/app-config.json"
